# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14message_status.proto\"M\n\rMessageStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x1a\n\rerror_message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_error_messageb\x06proto3')



_MESSAGESTATUS = DESCRIPTOR.message_types_by_name['MessageStatus']
MessageStatus = _reflection.GeneratedProtocolMessageType('MessageStatus', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGESTATUS,
  '__module__' : 'message_status_pb2'
  # @@protoc_insertion_point(class_scope:MessageStatus)
  })
_sym_db.RegisterMessage(MessageStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGESTATUS._serialized_start=24
  _MESSAGESTATUS._serialized_end=101
# @@protoc_insertion_point(module_scope)
